### ISSUE TITLE
$allHasMobileUsersUPN not being populated correctly

### ISSUE THREAD

**Issue by DaveBrophy** [MSEndpointMgr/AzureAD#3]
I'm not a coder so hopefully I'll explain this right.
On line 396 the query to find users with mobile numbers works but the following line
$allHasMobileUsersUPN = $allHasMobileUsers.userPrincipalName
doesn't contain UPNs. The UPN appear to be in $allHasMobileUsers.value.userPrincipalName
I added a line: $allHasMobileUsers = $allHasMobileUsers.value to get it working but I'm sure this could be resolved more elegantly.

Hope this helps,
David

**Comment by DaveBrophy** [comment]
An update to this. All my testing was with one user account being updated.
I ran another test today again with one user and I had to modify the script as above and it worked.
Then I added multiple users and found the script wasn't working.
I reverted back the change I made and then it worked.

**Comment by mardahl** [comment]
Yup. It's because it is expected to work with an array of users not a single user.
But I get why you test with just one.
