### ISSUE TITLE
Unsupported property filter clause operator 'NotEqualsMatch'. 

### ISSUE THREAD

**Issue by golubenkoff** [MSEndpointMgr/AzureAD#5]
Hi,

When executing:

 WARNING: Graph request failed with status code ''. Error message: Unsupported property filter clause operator 'NotEqualsMatch'. 

     $allHasMobileUsers = Invoke-MSGraphOperation -Get -APIVersion $graphVersion -Headers $authTokenApp -Resource 
    "users?count=true&select=userPrincipalName,mobilePhone&filter=userType ne 'Guest' and mobilePhone ne null" 

I think main issue that it is cannot execute filter  mobilePhone ne null

Based on  https://github.com/microsoftgraph/microsoft-graph-docs/blob/master/api-reference/v1.0/resources/user.md - mobilePhone doesn't support $filter

How to make it work?

**Comment by JankeSkanke** [comment]
Our authentication function handles this by adding Consistency Level - Eventual: 
authToken = @{
            Authorization = $response.CreateAuthorizationHeader()
            ConsistencyLevel = 'eventual'
        } 
   Read more here: 
   https://developer.microsoft.com/en-us/identity/blogs/microsoft-graph-advanced-queries-for-directory-objects-are-now-generally-available/
